workflows:
  build-ios:
    name: Build Cordova iOS app
    instance_type: mac_pro
    environment:
      vars:
        CORDOVA_PLATFORM: ios
      node: 18.16.0
      xcode: latest
    scripts:
      - npm install -g cordova
      - npm install
      - cordova platform add $CORDOVA_PLATFORM
      - cordova build ios --release
    artifacts:
      - platforms/ios/build/**/*.ipa
    publishing:
      email:
        recipients:
          - ngocmaieth@gmail.com
        notify:
          success: true
          failure: true



2. Thêm và push file lên GitHub:
git add codemagic.yaml
git commit -m "Add codemagic.yaml for iOS build"
git push

Chạy lệnh sau để push và set upstream luôn:
git push --set-upstream origin main


✅ Tiếp theo:
Quay lại Codemagic

Nhấn nút Check for configuration files

Nếu nhận file codemagic.yaml, bạn sẽ thấy nút Start new build